"""empty message

Revision ID: 2c9741bd94bf
Revises: 
Create Date: 2022-10-08 15:57:26.571708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9741bd94bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('country_abbrev', sa.String(length=3), nullable=False))
    op.create_unique_constraint(None, 'country', ['country_abbrev'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_column('country', 'country_abbrev')
    # ### end Alembic commands ###
